version: '3'
services:
  doctorapp-application-database:
    container_name: doctorapp-application-database
    image: postgres:11.3
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - data-store:/var/lib/postgresql/data:rw
    networks:
      - backend-network

  node:
    container_name: doctorapp-application-server
    image: "node:14.15.1"
    command: npm run start-local
    working_dir: /app
    ports:
      - "3333:3333"
    restart: always
    env_file: .env

    volumes:
      - ./:/app
    depends_on:
      - doctorapp-application-database
    networks:
      - backend-network

networks:
  backend-network:
volumes:
  data-store:
